=== sawsonu123-tech/GitFolder/Web Tech Labs/WT Lab 3/registrations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Bits ID: 1956www12345 - Heera Thakur -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registrations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="registration" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name="studentId">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
<!-- Bits ID: 1956www12345 - Heera Thakur -->
                            <xs:element name="studentName" type="xs:string"/>
                            <xs:element name="courseCode" type="xs:string"/>
                            <xs:element name="courseTitle" type="xs:string"/>
                            <xs:element name="semester" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sawsonu123-tech/GitFolder/Web Tech Labs/WT Lab 3/Final zip file/registrations.xml
<?xml version="1.0" encoding="UTF-8"?>
<registrations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="registrations.xsd">
    <registration>
        <studentId>-32</studentId>
        <studentName>dfs</studentName>
        <courseCode>fds</courseCode>
        <courseTitle></courseTitle>
        <semester></semester>
    </registration>
    <registration>
        <studentId>abc</studentId>
        <studentName>dsf</studentName>
        <courseCode>dfs</courseCode>
        <courseTitle>dfs</courseTitle>
        <semester>dsf</semester>
    </registration>
</registrations>
